language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install package
install:
  - python setup.py install
  - pip install coveralls
# command to run tests
script:
  - nosetests
  - nosetests --with-coverage --cover-package=SimplePool
after_success:
  coveralls
notifications:
  email: false
